version: '3'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pubquiz
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
