version: '3'

tasks:
  bootstrap:
    cmds:
      - pnpm install

  dev:
    cmds:
      - pnpm dev

  lint:
    cmds:
      - pnpm lint --fix

  test:
    cmds:
      - pnpm test

  storybook:
    cmds:
      - pnpm storybook

  build-storybook:
    cmds:
      - pnpm build-storybook
